name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: | 
                echo "Hello World!"
                echo "It's Dp World"
               
      - name: Set environment variable
        run: echo "MY_ENV_VAR=myValue" >> $GITHUB_ENV
      - name: print goodbye
        run: echo "Done -bye!"
      
        
