name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: | 
                echo "Hello World!"
                echo "It's Dp World"
                pwd
      - name: print goodbye
        run: echo "Done -bye!"
      
        
